part of 'slitherlink_foundation.dart';

final slitherlinkPuzzleCatalog = <SlitherlinkPuzzle>[
  const SlitherlinkPuzzle(
    id: 'slither_easy_01',
    title: 'Erste Ecken',
    rows: 5,
    columns: 5,
    difficulty: PuzzleDifficulty.easy,
    clues: [
      [0, 1, 1, 0, 0],
      [null, 2, null, 2, 1],
      [3, 1, 1, 1, null],
      [1, 1, 2, 3, 2],
      [0, null, 0, null, 0],
    ],
    solution: {
      'h:1:1',
      'h:1:2',
      'h:2:0',
      'h:2:3',
      'h:2:4',
      'h:3:0',
      'h:3:1',
      'h:3:2',
      'h:3:4',
      'h:4:3',
      'v:1:1',
      'v:1:3',
      'v:2:0',
      'v:2:5',
      'v:3:3',
      'v:3:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_easy_02',
    title: 'Kleine Runde',
    rows: 5,
    columns: 5,
    difficulty: PuzzleDifficulty.easy,
    clues: [
      [0, 1, 2, 3, 1],
      [0, 2, 2, 2, 0],
      [2, null, 1, null, 0],
      [3, 1, 2, null, null],
      [1, 1, null, 0, 0],
    ],
    solution: {
      'h:0:2',
      'h:0:3',
      'h:1:3',
      'h:2:1',
      'h:3:0',
      'h:4:0',
      'h:4:1',
      'h:4:2',
      'v:0:2',
      'v:0:4',
      'v:1:2',
      'v:1:3',
      'v:2:1',
      'v:2:3',
      'v:3:0',
      'v:3:3',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_easy_03',
    title: 'Sanfte Kurven',
    rows: 5,
    columns: 5,
    difficulty: PuzzleDifficulty.easy,
    clues: [
      [null, 2, 2, 2, 0],
      [2, 1, 0, null, 1],
      [3, 3, 3, null, 0],
      [null, 0, 1, 0, 0],
      [0, 0, 0, null, 0],
    ],
    solution: {
      'h:0:1',
      'h:0:2',
      'h:1:0',
      'h:1:3',
      'h:2:1',
      'h:2:3',
      'h:3:0',
      'h:3:2',
      'v:0:1',
      'v:0:3',
      'v:1:0',
      'v:1:4',
      'v:2:0',
      'v:2:1',
      'v:2:2',
      'v:2:3',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_easy_04',
    title: 'Am Rand entlang',
    rows: 5,
    columns: 5,
    difficulty: PuzzleDifficulty.easy,
    clues: [
      [0, 1, 3, 1, 0],
      [0, 2, null, 2, 0],
      [null, 2, 1, 3, 1],
      [null, 1, null, null, 0],
      [2, 3, 1, 0, 0],
    ],
    solution: {
      'h:0:2',
      'h:2:1',
      'h:2:3',
      'h:3:0',
      'h:3:2',
      'h:3:3',
      'h:4:0',
      'h:5:1',
      'v:0:2',
      'v:0:3',
      'v:1:2',
      'v:1:3',
      'v:2:1',
      'v:2:4',
      'v:3:0',
      'v:3:2',
      'v:4:1',
      'v:4:2',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_easy_05',
    title: 'Klare Spuren',
    rows: 5,
    columns: 5,
    difficulty: PuzzleDifficulty.easy,
    clues: [
      [null, null, 3, 1, 0],
      [3, 1, 1, 2, 1],
      [2, 2, null, 2, 3],
      [0, 1, null, 1, 1],
      [0, 0, 0, null, 0],
    ],
    solution: {
      'h:0:2',
      'h:1:0',
      'h:1:1',
      'h:2:0',
      'h:2:3',
      'h:2:4',
      'h:3:1',
      'h:3:2',
      'h:3:3',
      'h:3:4',
      'v:0:2',
      'v:0:3',
      'v:1:0',
      'v:1:3',
      'v:2:1',
      'v:2:5',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_easy_06',
    title: 'Kurzer Umweg',
    rows: 5,
    columns: 5,
    difficulty: PuzzleDifficulty.easy,
    clues: [
      [0, 0, 1, 0, 0],
      [1, 2, 3, 2, 0],
      [2, 1, 0, null, 1],
      [2, 1, null, null, 0],
      [null, 1, 1, null, 0],
    ],
    solution: {
      'h:1:2',
      'h:2:0',
      'h:2:1',
      'h:2:3',
      'h:3:3',
      'h:4:0',
      'h:4:1',
      'h:4:2',
      'v:1:2',
      'v:1:3',
      'v:2:0',
      'v:2:4',
      'v:3:0',
      'v:3:3',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_easy_07',
    title: 'Offene Hinweise',
    rows: 5,
    columns: 5,
    difficulty: PuzzleDifficulty.easy,
    clues: [
      [0, 0, 1, 0, null],
      [null, 1, 3, 1, null],
      [null, 2, 2, 2, 1],
      [1, 3, 0, null, 3],
      [0, 2, 2, 2, 2],
    ],
    solution: {
      'h:1:2',
      'h:3:1',
      'h:3:3',
      'h:3:4',
      'h:4:1',
      'h:4:4',
      'h:5:2',
      'h:5:3',
      'v:1:2',
      'v:1:3',
      'v:2:2',
      'v:2:3',
      'v:3:1',
      'v:3:5',
      'v:4:2',
      'v:4:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_easy_08',
    title: 'Ruhiger Pfad',
    rows: 5,
    columns: 5,
    difficulty: PuzzleDifficulty.easy,
    clues: [
      [0, null, 1, 3, null],
      [0, 1, 2, 1, null],
      [1, 2, 1, 2, 2],
      [1, null, 2, null, 0],
      [0, 1, 1, 0, 0],
    ],
    solution: {
      'h:0:3',
      'h:1:4',
      'h:2:1',
      'h:2:2',
      'h:2:4',
      'h:3:3',
      'h:4:1',
      'h:4:2',
      'v:0:3',
      'v:0:4',
      'v:1:3',
      'v:1:5',
      'v:2:1',
      'v:2:4',
      'v:3:1',
      'v:3:3',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_easy_09',
    title: 'Doppelte Ecke',
    rows: 5,
    columns: 5,
    difficulty: PuzzleDifficulty.easy,
    clues: [
      [0, null, 0, null, 0],
      [1, 3, 2, 0, 0],
      [1, null, 2, 2, 1],
      [1, 1, null, 2, 3],
      [null, 3, 2, 1, 1],
    ],
    solution: {
      'h:1:1',
      'h:2:2',
      'h:3:3',
      'h:3:4',
      'h:4:2',
      'h:4:3',
      'h:4:4',
      'h:5:1',
      'v:1:1',
      'v:1:2',
      'v:2:1',
      'v:2:3',
      'v:3:1',
      'v:3:5',
      'v:4:1',
      'v:4:2',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_easy_10',
    title: 'Weite Schleife',
    rows: 5,
    columns: 5,
    difficulty: PuzzleDifficulty.easy,
    clues: [
      [0, 0, 0, 0, 1],
      [0, 1, null, null, 3],
      [1, null, 2, 1, 1],
      [0, 1, 2, null, 2],
      [0, null, 1, 3, 2],
    ],
    solution: {
      'h:1:4',
      'h:2:1',
      'h:2:2',
      'h:2:3',
      'h:3:1',
      'h:3:2',
      'h:4:4',
      'h:5:3',
      'v:1:4',
      'v:1:5',
      'v:2:1',
      'v:2:5',
      'v:3:3',
      'v:3:5',
      'v:4:3',
      'v:4:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_easy_11',
    title: 'Sicher herum',
    rows: 5,
    columns: 5,
    difficulty: PuzzleDifficulty.easy,
    clues: [
      [0, 1, 1, 0, 0],
      [1, 2, null, 2, 0],
      [1, null, 0, 2, 2],
      [0, null, 2, null, 3],
      [0, 0, 1, 1, null],
    ],
    solution: {
      'h:1:1',
      'h:1:2',
      'h:2:3',
      'h:3:1',
      'h:3:4',
      'h:4:2',
      'h:4:3',
      'h:4:4',
      'v:1:1',
      'v:1:3',
      'v:2:1',
      'v:2:4',
      'v:3:2',
      'v:3:5',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_easy_12',
    title: 'Letzte Übung',
    rows: 5,
    columns: 5,
    difficulty: PuzzleDifficulty.easy,
    clues: [
      [0, 0, 0, 0, 0],
      [0, 1, 1, 1, 0],
      [1, 2, null, 3, 1],
      [1, 2, null, 3, null],
      [0, null, 2, null, 3],
    ],
    solution: {
      'h:2:1',
      'h:2:2',
      'h:2:3',
      'h:3:3',
      'h:4:1',
      'h:4:3',
      'h:4:4',
      'h:5:2',
      'h:5:3',
      'h:5:4',
      'v:2:1',
      'v:2:4',
      'v:3:1',
      'v:3:3',
      'v:4:2',
      'v:4:5',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_medium_01',
    title: 'Verdeckter Weg',
    rows: 6,
    columns: 6,
    difficulty: PuzzleDifficulty.medium,
    clues: [
      [0, 1, null, null, 0, 0],
      [1, null, null, 0, 0, 0],
      [1, 1, null, 2, null, 1],
      [null, 1, 0, 1, null, 2],
      [null, 2, 1, 1, 1, null],
      [0, 1, 1, null, 1, null],
    ],
    solution: {
      'h:1:1',
      'h:2:2',
      'h:3:3',
      'h:3:4',
      'h:3:5',
      'h:5:1',
      'h:5:2',
      'h:5:3',
      'h:5:4',
      'h:5:5',
      'v:1:1',
      'v:1:2',
      'v:2:1',
      'v:2:3',
      'v:3:1',
      'v:3:6',
      'v:4:1',
      'v:4:6',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_medium_02',
    title: 'Zwischen den Zahlen',
    rows: 6,
    columns: 6,
    difficulty: PuzzleDifficulty.medium,
    clues: [
      [0, null, 0, 1, 3, null],
      [0, 0, 0, null, 1, 2],
      [0, null, 2, 2, 1, 2],
      [1, 2, null, 1, 2, null],
      [null, 2, 1, null, null, 0],
      [0, null, 2, null, 1, null],
    ],
    solution: {
      'h:0:4',
      'h:1:5',
      'h:2:3',
      'h:3:1',
      'h:3:2',
      'h:3:4',
      'h:3:5',
      'h:5:1',
      'h:5:2',
      'h:6:3',
      'v:0:4',
      'v:0:5',
      'v:1:4',
      'v:1:6',
      'v:2:3',
      'v:2:6',
      'v:3:1',
      'v:3:4',
      'v:4:1',
      'v:4:4',
      'v:5:3',
      'v:5:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_medium_03',
    title: 'Geteilte Spuren',
    rows: 6,
    columns: 6,
    difficulty: PuzzleDifficulty.medium,
    clues: [
      [1, 3, 3, null, null, null],
      [null, 1, null, 0, 3, null],
      [1, 2, 1, null, null, 0],
      [null, 1, 2, 1, null, 1],
      [0, 0, 1, 2, null, 0],
      [0, null, 1, 3, 1, 0],
    ],
    solution: {
      'h:0:1',
      'h:0:3',
      'h:1:2',
      'h:1:4',
      'h:2:4',
      'h:3:1',
      'h:3:2',
      'h:3:4',
      'h:4:4',
      'h:6:3',
      'v:0:1',
      'v:0:2',
      'v:0:3',
      'v:0:4',
      'v:1:1',
      'v:1:5',
      'v:2:1',
      'v:2:4',
      'v:3:3',
      'v:3:5',
      'v:4:3',
      'v:4:4',
      'v:5:3',
      'v:5:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_medium_04',
    title: 'Enge Kurven',
    rows: 6,
    columns: 6,
    difficulty: PuzzleDifficulty.medium,
    clues: [
      [null, null, 0, null, 1, null],
      [null, 0, 1, 2, 2, 1],
      [null, 0, null, null, null, 2],
      [0, 2, 2, 0, 1, 3],
      [1, 3, null, 1, null, null],
      [0, 2, 2, 2, 1, 0],
    ],
    solution: {
      'h:1:3',
      'h:1:4',
      'h:3:2',
      'h:3:5',
      'h:4:1',
      'h:4:4',
      'h:4:5',
      'h:5:1',
      'h:6:2',
      'h:6:3',
      'v:1:3',
      'v:1:5',
      'v:2:3',
      'v:2:5',
      'v:3:2',
      'v:3:6',
      'v:4:1',
      'v:4:4',
      'v:5:2',
      'v:5:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_medium_05',
    title: 'Unerwartete Wende',
    rows: 6,
    columns: 6,
    difficulty: PuzzleDifficulty.medium,
    clues: [
      [0, 0, null, 0, 0, 0],
      [0, 1, null, 1, null, 0],
      [null, 2, 1, 1, null, 1],
      [1, 1, 0, 0, 1, null],
      [1, null, 1, null, null, null],
      [0, null, null, 3, 2, 0],
    ],
    solution: {
      'h:2:1',
      'h:2:2',
      'h:2:3',
      'h:2:4',
      'h:5:1',
      'h:5:2',
      'h:5:4',
      'h:6:3',
      'v:2:1',
      'v:2:5',
      'v:3:1',
      'v:3:5',
      'v:4:1',
      'v:4:5',
      'v:5:3',
      'v:5:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_medium_06',
    title: 'Langer Umweg',
    rows: 6,
    columns: 6,
    difficulty: PuzzleDifficulty.medium,
    clues: [
      [null, 0, null, 2, 2, null],
      [0, 0, 2, 1, 1, 1],
      [0, 1, 2, null, 1, null],
      [0, 2, 1, 0, 2, null],
      [null, null, 1, 2, 2, 0],
      [null, null, 1, null, 0, null],
    ],
    solution: {
      'h:0:3',
      'h:0:4',
      'h:2:2',
      'h:4:1',
      'h:4:4',
      'h:5:1',
      'h:5:2',
      'h:5:3',
      'v:0:3',
      'v:0:5',
      'v:1:3',
      'v:1:5',
      'v:2:2',
      'v:2:5',
      'v:3:2',
      'v:3:5',
      'v:4:1',
      'v:4:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_medium_07',
    title: 'Im Gleichgewicht',
    rows: 6,
    columns: 6,
    difficulty: PuzzleDifficulty.medium,
    clues: [
      [null, null, null, 3, 1, 0],
      [1, 3, 1, 1, null, null],
      [0, null, 1, 0, 2, 2],
      [0, 1, 1, 0, 1, 3],
      [0, null, null, null, 2, 1],
      [null, 0, 1, null, 0, null],
    ],
    solution: {
      'h:0:3',
      'h:1:1',
      'h:1:2',
      'h:2:1',
      'h:2:4',
      'h:3:5',
      'h:4:4',
      'h:4:5',
      'h:5:2',
      'h:5:3',
      'v:0:3',
      'v:0:4',
      'v:1:1',
      'v:1:4',
      'v:2:2',
      'v:2:5',
      'v:3:2',
      'v:3:6',
      'v:4:2',
      'v:4:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_medium_08',
    title: 'Kreuz und quer',
    rows: 6,
    columns: 6,
    difficulty: PuzzleDifficulty.medium,
    clues: [
      [0, 1, 1, 1, null, 0],
      [null, null, null, 2, 1, 0],
      [3, 0, null, 1, 2, 1],
      [null, 2, 0, 1, null, 3],
      [null, 2, 3, 2, 1, null],
      [null, 0, null, null, 0, 0],
    ],
    solution: {
      'h:1:1',
      'h:1:2',
      'h:1:3',
      'h:2:0',
      'h:3:0',
      'h:3:4',
      'h:3:5',
      'h:4:1',
      'h:4:3',
      'h:4:4',
      'h:4:5',
      'h:5:2',
      'v:1:1',
      'v:1:4',
      'v:2:0',
      'v:2:4',
      'v:3:1',
      'v:3:6',
      'v:4:2',
      'v:4:3',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_medium_09',
    title: 'Schmale Passage',
    rows: 6,
    columns: 6,
    difficulty: PuzzleDifficulty.medium,
    clues: [
      [0, null, 0, 0, 0, 0],
      [null, 0, 1, null, 1, null],
      [0, 2, 2, 1, 2, 1],
      [null, null, null, 0, null, 2],
      [null, 2, 1, null, 1, 2],
      [null, 1, 3, 2, 2, null],
    ],
    solution: {
      'h:2:2',
      'h:2:3',
      'h:2:4',
      'h:3:1',
      'h:4:1',
      'h:4:5',
      'h:5:3',
      'h:5:4',
      'h:6:2',
      'h:6:5',
      'v:2:2',
      'v:2:5',
      'v:3:1',
      'v:3:5',
      'v:4:2',
      'v:4:6',
      'v:5:2',
      'v:5:3',
      'v:5:5',
      'v:5:6',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_medium_10',
    title: 'Tiefe Schleife',
    rows: 6,
    columns: 6,
    difficulty: PuzzleDifficulty.medium,
    clues: [
      [0, 0, 0, null, 0, 0],
      [0, 0, null, null, 1, 0],
      [0, 1, null, 1, 2, null],
      [0, null, 1, 0, 1, 1],
      [null, null, null, 0, null, 1],
      [0, 2, null, 1, 2, null],
    ],
    solution: {
      'h:2:2',
      'h:2:3',
      'h:2:4',
      'h:4:1',
      'h:5:1',
      'h:6:2',
      'h:6:3',
      'h:6:4',
      'v:2:2',
      'v:2:5',
      'v:3:2',
      'v:3:5',
      'v:4:1',
      'v:4:5',
      'v:5:2',
      'v:5:5',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_medium_11',
    title: 'Viele Möglichkeiten',
    rows: 6,
    columns: 6,
    difficulty: PuzzleDifficulty.medium,
    clues: [
      [null, null, 1, 2, 2, null],
      [null, 0, 1, 1, null, 1],
      [1, 1, 2, 1, null, 1],
      [3, 1, null, null, 2, null],
      [null, 3, 3, 3, 2, 0],
      [0, null, null, 1, 0, 0],
    ],
    solution: {
      'h:0:3',
      'h:0:4',
      'h:3:0',
      'h:3:1',
      'h:3:2',
      'h:4:0',
      'h:4:2',
      'h:4:4',
      'h:5:1',
      'h:5:3',
      'v:0:3',
      'v:0:5',
      'v:1:3',
      'v:1:5',
      'v:2:3',
      'v:2:5',
      'v:3:0',
      'v:3:5',
      'v:4:1',
      'v:4:2',
      'v:4:3',
      'v:4:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_medium_12',
    title: 'Sicher kombiniert',
    rows: 6,
    columns: 6,
    difficulty: PuzzleDifficulty.medium,
    clues: [
      [0, null, 0, 0, 0, 0],
      [2, 3, null, 1, 0, null],
      [2, null, null, 3, 2, 0],
      [1, 1, 1, null, 3, null],
      [3, null, 2, 1, 2, 0],
      [null, null, 2, null, 1, null],
    ],
    solution: {
      'h:1:1',
      'h:2:0',
      'h:2:3',
      'h:3:2',
      'h:3:4',
      'h:4:1',
      'h:4:4',
      'h:5:0',
      'h:5:2',
      'h:6:3',
      'v:1:1',
      'v:1:2',
      'v:2:0',
      'v:2:2',
      'v:2:3',
      'v:2:4',
      'v:3:0',
      'v:3:5',
      'v:4:0',
      'v:4:1',
      'v:4:2',
      'v:4:4',
      'v:5:3',
      'v:5:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_hard_01',
    title: 'Wenige Spuren',
    rows: 7,
    columns: 7,
    difficulty: PuzzleDifficulty.hard,
    clues: [
      [0, 0, 0, 0, 0, null, null],
      [null, 1, 1, null, null, 1, 0],
      [2, 1, 2, 2, 2, 3, 1],
      [null, 0, null, null, null, 1, 1],
      [1, null, 1, 2, null, null, null],
      [null, null, 2, 1, null, 1, null],
      [2, 2, 1, null, 0, 0, null],
    ],
    solution: {
      'h:2:0',
      'h:2:1',
      'h:2:2',
      'h:2:5',
      'h:3:3',
      'h:3:4',
      'h:4:4',
      'h:5:2',
      'h:5:3',
      'h:5:5',
      'h:7:0',
      'h:7:1',
      'v:2:0',
      'v:2:3',
      'v:2:5',
      'v:2:6',
      'v:3:0',
      'v:3:6',
      'v:4:0',
      'v:4:4',
      'v:4:5',
      'v:4:6',
      'v:5:0',
      'v:5:2',
      'v:6:0',
      'v:6:2',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_hard_02',
    title: 'Falsche Fährten',
    rows: 7,
    columns: 7,
    difficulty: PuzzleDifficulty.hard,
    clues: [
      [0, 1, 1, null, 3, 1, null],
      [2, 2, null, 1, 1, 1, 0],
      [null, null, null, 0, null, null, null],
      [2, 1, 0, 0, null, null, 0],
      [null, 2, 1, null, null, null, null],
      [0, null, 3, 2, 1, 0, 0],
      [0, null, 1, null, 0, 0, 0],
    ],
    solution: {
      'h:0:4',
      'h:1:1',
      'h:1:2',
      'h:1:3',
      'h:2:0',
      'h:4:0',
      'h:4:1',
      'h:5:3',
      'h:5:4',
      'h:6:2',
      'v:0:4',
      'v:0:5',
      'v:1:1',
      'v:1:5',
      'v:2:0',
      'v:2:5',
      'v:3:0',
      'v:3:5',
      'v:4:2',
      'v:4:5',
      'v:5:2',
      'v:5:3',
    },
  ),
  _catalogPuzzleFromSeed(
    id: 'slither_hard_03',
    title: 'Verborgene Schleife',
    seed: 23075,
    difficulty: PuzzleDifficulty.hard,
  ),
  const SlitherlinkPuzzle(
    id: 'slither_hard_04',
    title: 'Knappe Entscheidung',
    rows: 7,
    columns: 7,
    difficulty: PuzzleDifficulty.hard,
    clues: [
      [0, 0, 0, 1, 0, null, 0],
      [null, 0, null, null, 2, null, 1],
      [0, null, null, 1, null, 1, null],
      [0, null, 2, 0, 0, 1, null],
      [null, 2, null, 0, 1, 2, 1],
      [1, 3, 1, 0, null, 1, 0],
      [null, 1, null, 2, null, null, null],
    ],
    solution: {
      'h:1:3',
      'h:2:4',
      'h:2:5',
      'h:2:6',
      'h:3:2',
      'h:4:5',
      'h:4:6',
      'h:5:1',
      'h:6:1',
      'h:6:2',
      'h:7:3',
      'h:7:4',
      'v:1:3',
      'v:1:4',
      'v:2:3',
      'v:2:7',
      'v:3:2',
      'v:3:7',
      'v:4:2',
      'v:4:5',
      'v:5:1',
      'v:5:5',
      'v:6:3',
      'v:6:5',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_hard_05',
    title: 'Dichter Nebel',
    rows: 7,
    columns: 7,
    difficulty: PuzzleDifficulty.hard,
    clues: [
      [0, 0, null, 0, 1, 0, 0],
      [0, null, 3, null, 3, null, null],
      [null, null, 0, null, 1, null, null],
      [3, 0, null, 0, 0, 2, 1],
      [2, null, 1, 1, 1, 1, null],
      [null, null, 2, null, 2, 3, 1],
      [null, 1, null, null, 0, 1, 0],
    ],
    solution: {
      'h:1:2',
      'h:1:4',
      'h:2:1',
      'h:2:3',
      'h:3:0',
      'h:3:5',
      'h:4:0',
      'h:5:2',
      'h:5:3',
      'h:5:4',
      'h:6:1',
      'h:6:5',
      'v:1:2',
      'v:1:3',
      'v:1:4',
      'v:1:5',
      'v:2:1',
      'v:2:5',
      'v:3:0',
      'v:3:6',
      'v:4:1',
      'v:4:6',
      'v:5:1',
      'v:5:2',
      'v:5:5',
      'v:5:6',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_hard_06',
    title: 'Langer Gedanke',
    rows: 7,
    columns: 7,
    difficulty: PuzzleDifficulty.hard,
    clues: [
      [0, 1, null, null, 0, 0, null],
      [1, null, 2, 2, 0, 0, null],
      [1, 1, null, null, 2, null, 0],
      [1, null, 0, 0, 1, null, 1],
      [1, null, null, null, 1, null, 0],
      [0, 2, 2, 0, null, 1, 0],
      [null, null, 2, null, 2, 1, null],
    ],
    solution: {
      'h:1:1',
      'h:1:2',
      'h:2:3',
      'h:3:4',
      'h:3:5',
      'h:4:5',
      'h:5:1',
      'h:6:2',
      'h:7:3',
      'h:7:4',
      'v:1:1',
      'v:1:3',
      'v:2:1',
      'v:2:4',
      'v:3:1',
      'v:3:6',
      'v:4:1',
      'v:4:5',
      'v:5:2',
      'v:5:5',
      'v:6:3',
      'v:6:5',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_hard_07',
    title: 'Meisterhafte Kurven',
    rows: 7,
    columns: 7,
    difficulty: PuzzleDifficulty.hard,
    clues: [
      [null, 0, null, null, 2, 2, 1],
      [0, null, 2, 1, null, null, 2],
      [0, null, 1, 0, 0, null, 2],
      [null, null, 2, 0, 0, null, null],
      [0, 0, 2, 2, null, 2, null],
      [null, 0, 0, 1, 1, 1, 0],
      [null, 0, null, 0, 0, null, null],
    ],
    solution: {
      'h:0:4',
      'h:0:5',
      'h:1:2',
      'h:1:3',
      'h:2:6',
      'h:4:2',
      'h:4:6',
      'h:5:3',
      'h:5:4',
      'h:5:5',
      'v:0:4',
      'v:0:6',
      'v:1:2',
      'v:1:6',
      'v:2:2',
      'v:2:7',
      'v:3:2',
      'v:3:7',
      'v:4:3',
      'v:4:6',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_hard_08',
    title: 'Ohne Umweg',
    rows: 7,
    columns: 7,
    difficulty: PuzzleDifficulty.hard,
    clues: [
      [null, 0, 0, null, null, 0, null],
      [null, 0, 0, 1, 0, null, 0],
      [0, 1, 2, null, 2, null, null],
      [null, 2, 1, 0, 1, null, 3],
      [2, 1, 0, null, 0, 2, null],
      [null, 1, 0, 0, null, 2, null],
      [1, 2, null, 2, null, null, 0],
    ],
    solution: {
      'h:2:3',
      'h:3:1',
      'h:3:2',
      'h:3:4',
      'h:3:5',
      'h:3:6',
      'h:4:6',
      'h:5:0',
      'h:5:5',
      'h:6:0',
      'h:6:1',
      'h:6:4',
      'h:7:2',
      'h:7:3',
      'v:2:3',
      'v:2:4',
      'v:3:1',
      'v:3:7',
      'v:4:1',
      'v:4:6',
      'v:5:0',
      'v:5:5',
      'v:6:2',
      'v:6:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_hard_09',
    title: 'Schwierige Balance',
    rows: 7,
    columns: 7,
    difficulty: PuzzleDifficulty.hard,
    clues: [
      [null, 2, 1, 1, 2, null, 0],
      [null, 0, null, 0, 1, 1, null],
      [null, 1, null, null, 1, 1, 0],
      [null, 1, 1, null, 2, null, 0],
      [1, null, 3, 3, 2, null, 0],
      [0, 1, null, 1, null, 0, 0],
      [null, 0, null, 0, 0, null, null],
    ],
    solution: {
      'h:0:1',
      'h:0:2',
      'h:0:3',
      'h:0:4',
      'h:1:0',
      'h:2:0',
      'h:4:2',
      'h:4:4',
      'h:5:1',
      'h:5:3',
      'v:0:1',
      'v:0:5',
      'v:1:0',
      'v:1:5',
      'v:2:1',
      'v:2:5',
      'v:3:1',
      'v:3:5',
      'v:4:1',
      'v:4:2',
      'v:4:3',
      'v:4:4',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_hard_10',
    title: 'Letzte Hinweise',
    rows: 7,
    columns: 7,
    difficulty: PuzzleDifficulty.hard,
    clues: [
      [null, 0, null, 1, null, null, 1],
      [null, 2, null, 1, 1, 1, null],
      [null, 2, 0, 0, 0, 0, 2],
      [null, 2, null, null, 1, 1, 2],
      [0, 2, null, 2, null, 3, null],
      [0, null, null, 1, 0, 1, 0],
      [null, 0, 0, null, 0, null, 0],
    ],
    solution: {
      'h:1:2',
      'h:1:3',
      'h:1:4',
      'h:1:5',
      'h:1:6',
      'h:2:1',
      'h:3:6',
      'h:4:1',
      'h:4:4',
      'h:5:2',
      'h:5:3',
      'h:5:5',
      'v:1:2',
      'v:1:7',
      'v:2:1',
      'v:2:7',
      'v:3:1',
      'v:3:6',
      'v:4:2',
      'v:4:4',
      'v:4:5',
      'v:4:6',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_hard_11',
    title: 'Große Prüfung',
    rows: 7,
    columns: 7,
    difficulty: PuzzleDifficulty.hard,
    clues: [
      [0, 1, null, null, 1, 0, 0],
      [0, null, null, null, 2, null, null],
      [1, 2, 0, 0, 0, null, null],
      [null, 2, 0, 1, 0, null, 2],
      [0, null, null, null, 3, 2, 1],
      [0, null, 3, 1, 1, null, null],
      [0, null, null, 0, 0, 0, 0],
    ],
    solution: {
      'h:0:2',
      'h:1:3',
      'h:1:4',
      'h:2:1',
      'h:2:5',
      'h:2:6',
      'h:4:1',
      'h:4:3',
      'h:4:5',
      'h:4:6',
      'h:5:4',
      'h:6:2',
      'v:0:2',
      'v:0:3',
      'v:1:2',
      'v:1:5',
      'v:2:1',
      'v:2:7',
      'v:3:1',
      'v:3:7',
      'v:4:2',
      'v:4:3',
      'v:4:4',
      'v:4:5',
      'v:5:2',
      'v:5:3',
    },
  ),
  const SlitherlinkPuzzle(
    id: 'slither_hard_12',
    title: 'Meisterschleife',
    rows: 7,
    columns: 7,
    difficulty: PuzzleDifficulty.hard,
    clues: [
      [2, 2, 2, null, null, 0, 0],
      [3, 0, null, null, null, 2, 0],
      [null, null, null, 0, 0, 3, 1],
      [1, null, 1, null, 2, 2, 0],
      [null, 1, 2, null, 3, 0, null],
      [0, 0, null, 2, null, 1, 0],
      [0, 0, null, null, null, 0, null],
    ],
    solution: {
      'h:0:1',
      'h:0:2',
      'h:1:0',
      'h:1:3',
      'h:1:4',
      'h:2:0',
      'h:2:5',
      'h:3:5',
      'h:4:1',
      'h:4:2',
      'h:4:4',
      'h:5:4',
      'h:6:3',
      'h:6:4',
      'v:0:1',
      'v:0:3',
      'v:1:0',
      'v:1:5',
      'v:2:1',
      'v:2:6',
      'v:3:1',
      'v:3:5',
      'v:4:3',
      'v:4:4',
      'v:5:3',
      'v:5:5',
    },
  ),
];
