import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:project_logic_prototype/features/hashi/domain/hashi_generator.dart';
import 'package:project_logic_prototype/hashi_foundation.dart';

void main() {
  test('generate static Hashi catalog', () {
    const generator = HashiGenerator();
    final specifications = <({int id, int difficulty})>[
      for (var id = 13; id <= 27; id++) (id: id, difficulty: 1),
      (id: 4, difficulty: 2),
      (id: 7, difficulty: 2),
      for (var id = 28; id <= 39; id++) (id: id, difficulty: 2),
      (id: 10, difficulty: 3),
      (id: 12, difficulty: 3),
      for (var id = 40; id <= 50; id++) (id: id, difficulty: 3),
      for (var id = 51; id <= 53; id++) (id: id, difficulty: 1),
      for (var id = 54; id <= 56; id++) (id: id, difficulty: 2),
      for (var id = 57; id <= 60; id++) (id: id, difficulty: 3),
    ];
    final puzzles = <HashiPuzzle>[];
    for (final specification in specifications) {
      final generated = generator.generate(
        seed: 730000 + specification.id * 97 + specification.difficulty,
        number: specification.id,
        difficulty: specification.difficulty,
      );
      final source = generated.puzzle;
      puzzles.add(HashiPuzzle(
        id: 'hashi_${specification.id.toString().padLeft(2, '0')}',
        title: switch (specification.difficulty) {
          1 => 'Brückenweg ${specification.id}',
          2 => 'Inselnetz ${specification.id}',
          _ => 'Meisterbrücken ${specification.id}',
        },
        size: source.size,
        difficulty: source.difficulty,
        islands: source.islands,
        solution: source.solution,
      ));
    }

    final output = StringBuffer()
      ..writeln("part of 'hashi_foundation.dart';")
      ..writeln()
      ..writeln('// ignore_for_file: prefer_const_constructors, '
          'prefer_const_literals_to_create_immutables')
      ..writeln()
      ..writeln('// Generated by tool/generate_hashi_catalog_test.dart.')
      ..writeln('// Every puzzle is connected and uniquely solvable.')
      ..writeln('final generatedHashiPuzzleCatalog = <HashiPuzzle>[');
    for (final puzzle in puzzles) {
      _writePuzzle(output, puzzle);
    }
    output.writeln('];');
    File('lib/generated_hashi_catalog.dart')
        .writeAsStringSync(output.toString());
    expect(puzzles, hasLength(52));
  });
}

void _writePuzzle(StringBuffer output, HashiPuzzle puzzle) {
  output
    ..writeln('  HashiPuzzle(')
    ..writeln("    id: '${puzzle.id}',")
    ..writeln("    title: '${puzzle.title}',")
    ..writeln('    size: ${puzzle.size},')
    ..writeln('    difficulty: ${puzzle.difficulty},')
    ..writeln('    islands: [');
  for (final island in puzzle.islands) {
    output.writeln(
      '      HashiIsland(row: ${island.row}, column: ${island.column}, bridges: ${island.bridges}),',
    );
  }
  output
    ..writeln('    ],')
    ..writeln('    solution: [');
  for (final bridge in puzzle.solution) {
    output.writeln(
      '      HashiBridge(from: ${bridge.from}, to: ${bridge.to}, count: ${bridge.count}),',
    );
  }
  output
    ..writeln('    ],')
    ..writeln('  ),');
}
