import 'dart:io';

import 'package:project_logic_prototype/features/binary_puzzle/domain/binary_puzzle_generator.dart';
import 'package:project_logic_prototype/game_logic.dart';

const targets = <int, Map<PuzzleDifficulty, int>>{
  4: {
    PuzzleDifficulty.easy: 8,
    PuzzleDifficulty.medium: 4,
    PuzzleDifficulty.hard: 2
  },
  6: {
    PuzzleDifficulty.easy: 7,
    PuzzleDifficulty.medium: 7,
    PuzzleDifficulty.hard: 5
  },
  8: {
    PuzzleDifficulty.easy: 6,
    PuzzleDifficulty.medium: 10,
    PuzzleDifficulty.hard: 10
  },
  10: {
    PuzzleDifficulty.easy: 2,
    PuzzleDifficulty.medium: 4,
    PuzzleDifficulty.hard: 6
  },
};

void main(List<String> arguments) {
  const generator = BinaryPuzzleGenerator();
  final selected = <({BinaryPuzzleDefinition definition, int seed})>[];
  final fingerprints = <String>{};
  final numbers = <PuzzleDifficulty, int>{
    for (final difficulty in PuzzleDifficulty.values) difficulty: 4,
  };

  for (final sizeEntry in targets.entries) {
    for (final targetEntry in sizeEntry.value.entries) {
      var found = 0;
      for (var candidate = 0; found < targetEntry.value; candidate++) {
        if (candidate >= 10000) {
          throw StateError(
            'Not enough ${sizeEntry.key} ${targetEntry.key.name} puzzles.',
          );
        }
        final requested =
            PuzzleDifficulty.values[(candidate + targetEntry.key.index) % 3];
        final seed = sizeEntry.key * 10000000 +
            targetEntry.key.index * 1000000 +
            candidate;
        final generated = generator.generate(
          size: sizeEntry.key,
          seed: seed,
          difficulty: requested,
        );
        final analysis = generated.difficultyAnalysis;
        if (!analysis.solvedLogically ||
            analysis.inferredDifficulty != targetEntry.key ||
            !fingerprints.add(_fingerprint(generated.definition))) {
          continue;
        }
        selected.add((
          definition: BinaryPuzzleDefinition(
            id: 'collection-${sizeEntry.key}-${targetEntry.key.name}-$seed',
            number: numbers[targetEntry.key]!,
            difficulty: targetEntry.key,
            solution: generated.definition.solution,
            clues: generated.definition.clues,
          ),
          seed: seed,
        ));
        numbers.update(targetEntry.key, (number) => number + 1);
        found++;
      }
    }
  }

  final output = StringBuffer()
    ..writeln("part of 'game_logic.dart';")
    ..writeln()
    ..writeln('// ignore_for_file: prefer_const_constructors')
    ..writeln()
    ..writeln('// Generated by tool/generate_binary_catalog.dart.')
    ..writeln('// Every puzzle is uniquely solvable and technique-rated.')
    ..writeln('final generatedBinaryPuzzleCatalog = <BinaryPuzzleDefinition>[');
  for (final item in selected) {
    _writeDefinition(output, item.definition, item.seed);
  }
  output.writeln('];');

  final target =
      arguments.isEmpty ? 'lib/generated_binary_catalog.dart' : arguments.first;
  File(target).writeAsStringSync(output.toString());
  stdout.writeln('Wrote ${selected.length} puzzles to $target.');
}

String _fingerprint(BinaryPuzzleDefinition definition) {
  final solution = definition.solution
      .expand((row) => row)
      .map((value) => value == CellValue.zero ? '0' : '1')
      .join();
  final clues = definition.clues.toList()..sort(_compareCells);
  return '$solution|${clues.map((cell) => '${cell.row}:${cell.column}').join(',')}';
}

int _compareCells(CellPosition a, CellPosition b) =>
    a.row == b.row ? a.column.compareTo(b.column) : a.row.compareTo(b.row);

void _writeDefinition(
  StringBuffer output,
  BinaryPuzzleDefinition definition,
  int seed,
) {
  output
    ..writeln('  BinaryPuzzleDefinition(')
    ..writeln("    id: '${definition.id}',")
    ..writeln('    number: ${definition.number},')
    ..writeln('    difficulty: PuzzleDifficulty.${definition.difficulty.name},')
    ..writeln('    solution: [');
  for (final row in definition.solution) {
    output.writeln(
      '      [${row.map((value) => 'CellValue.${value.name}').join(', ')}],',
    );
  }
  output
    ..writeln('    ],')
    ..writeln('    clues: {');
  final clues = definition.clues.toList()..sort(_compareCells);
  for (final clue in clues) {
    output.writeln('      CellPosition(${clue.row}, ${clue.column}),');
  }
  output
    ..writeln('    },')
    ..writeln('  ), // seed $seed');
}
